[package]
name = "advent2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dict = "0.1.5"
nom = "7.1.3"
regex = "1.10.2"
serde_json = "1.0.108"
simple-log = "1.6.0"
